# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#24273a'
foreground = '#f5bde6'

# Normal colors
[colors.normal]
black = '#1e2030'
red = '#ed8796'
green = '#a6da95'
yellow = '#eed49f'
blue = '#8aadf4'
magenta = '#c6a0f6'
cyan = '#8bd5ca'
white = '#cad3f5'

# Bright colors (same as normal colors)
[colors.bright]
black = '#c6a0f6'
red = '#ed8796'
green = '#a6da95'
yellow = '#eed49f'
blue = '#8aadf4'
magenta = '#c6a0f6'
cyan = '#8bd5ca'
white = '#cad3f5'

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.padding]
x = 20
y = 20
